galaxy_info:
  role_name: file_server
  author: Joe Shonk
  description: Install/Remove the Windows Role File Server
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - 2016
     - 2019

  galaxy_tags:
    - windows
    - file
    - fileserver
    - server

dependencies: []
